title: "Nebero Documentation"
author: "Inderpreet Singh"
description: "A Jekyll blog to document my work."
baseurl: "/nebero" 
url: "https://inder-singh001.github.io"  # Change this if hosting on GitHub Pages
paginate: 5

# Build settings
theme: null


# Navigation links
navbar:
  - title: "Week 1"
    url: "/2025/01/01/week1"
  - title: "Week 2"
    url: "/2025/01/01/week2"
  - title: "Week 3"
    url: "/2025/01/01/week3"
  - title: "Week 4"
    url: "/2025/01/01/week4"
  - title: "Week 5"
    url: "/2025/01/01/week5"
  - title: "Week 6"
    url: "/2025/01/01/week6"
  - title: "Week 7"
    url: "/2025/01/01/week7"
  - title: "Week 8"
    url: "/2025/01/01/week8"
  - title: "Week 9"
    url: "/2025/01/01/week9"
  - title: "Week 10"
    url: "/2025/01/01/week10"
  - title: "Home"
    url: "/"
  - title: "Introduction"
    url: "/2025/01/01/introduction"
  - title: "Data Collection"
    url: "/2025/01/02/data-collection"
  - title: "Scraping"
    url: "/2025/01/03/scraping"
  - title: "Problems in Web Scraping"
    url: "/2025/01/04/problems"
  - title: "Scraping Learning"
    url: "/2025/01/05/scraping-learning"
  - title: "Keyword Extraction"
    url: "/2025/01/06/keywords"
  - title: "Clustering Explanation"
    url: "/2025/01/07/clustering-explain"
  - title: "K-Means Clustering"
    url: "/2025/01/08/k-means"
  - title: "Faiss Clustering"
    url: "/2025/01/09/faiss"
  - title: "Clustering GPU Acceleration"
    url: "/2025/01/10/gpu-clustering"
  - title: "Using LLM Models"
    url: "/2025/01/31/llm-models"
  - title: "Hardware Requirements"
    url: "/2025/02/01/requirements"
  - title: "Requirements Evaluation"
    url: "/2025/02/13/cpuvgpu"
  - title: "Translation Model"
    url: "/2025/02/14/translation"
  - title: "RTX 4090"
    url: "/2025/02/16/rtx-4090"
  - title: "Feb 17"
    url: "/2025/02/17/feb-17"

# Exclude any files from Jekyll's processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Build settings
markdown: kramdown
theme: minima
paginate: 5

# Enable plugins (optional)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
