theme: minima

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "Introduction"
    url: "/2025/01/01/introduction"
  - title: "Data Collection"
    url: "/2025/01/02/data-collection"
  - title: "Scraping"
    url: "/2025/01/03/scraping"
  - title: "Problems in web scraping"
    url: "/2025/01/04/problems"
  - title: "Hardware Requirements and GPU Decision for AI Models"
    url: "/2025/02/13/cpuvgpu"
  - title: "Multilingual Data Translation and Model Evaluation"
    url: "/2025/02/14/translation"
  - title: "Setup of RTX 4090 and Model Experimentation"
    url: "/2025/02/16/rtx-4090"
  - title: "Feb 17"
    url: "/2025/02/17/feb-17"
