theme: minima

# Navigation links
navbar:
  - title: "Home"
    url: "/"
  - title: "Introduction"
    url: "/2025/01/01-introduction/"
  - title: "Data Collection"
    url: "/2025/01/02-data-collection/"
  - title: "Scraping"
    url: "/2025/01/03-scraping/"
  - title: "Problems"
    url: "/2025/01/04-problems/"
  - title: "Feb 13"
    url: "/2025/02/13-feb-13/"
  - title: "Feb 14"
    url: "/2025/02/14-feb-14/"
  - title: "Feb 16"
    url: "/2025/02/16-feb-16/"
  - title: "Feb 17"
    url: "/2025/02/17-feb-17/"
  - title: "Links"
    url: "/links.html"
